spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mysql://47.113.147.222:3306/work?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: work
    password: work

  cloud:
    nacos:
      discovery:
        server-addr: 47.113.147.222:8848

server:
  port: 8081


