server:
  port: 8080



spring:
  application:
    name: gateway-service
  cloud:
    nacos:
      discovery:
        server-addr: 47.113.147.222:8848
        cluster-name: nchu
    loadbalancer:
      nacos:
        enabled: true
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            # 允许携带认证信息
            allow-credentials: true
            # 允许跨域的源(网站域名/ip)，设置*为全部
            allowedOriginPatterns: "*"
            # 允许跨域的method， 默认为GET和OPTIONS，设置*为全部
            allowedMethods: "*"
            # 允许跨域请求里的head字段，设置*为全部
            allowedHeaders: "*"

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      # 配置路由，注意这里是个列表，每一项都包含了很多信息
      routes:
        - id: requirement   # 路由名称
          uri: lb://requirement-service  # 路由的地址，lb表示使用负载均衡到微服务，也可以使用http正常转发
          predicates: # 路由规则，断言什么请求会被路由
            - Path=/project/**,/epic/**,/characteristic/**,/story/**  # 只要是访问的这个路径，一律都被路由到上面指定的服务


        - id: sprint   # 路由名称
          uri: lb://sprint-service  # 路由的地址，lb表示使用负载均衡到微服务，也可以使用http正常转发
          predicates: # 路由规则，断言什么请求会被路由
            - Path=/sprint/**,/work/**  # 只要是访问的这个路径，一律都被路由到上面指定的服务

        - id:  user  # 路由名称
          uri: lb://user-service  # 路由的地址，lb表示使用负载均衡到微服务，也可以使用http正常转发
          predicates: # 路由规则，断言什么请求会被路由
            - Path=/user/**,/team/**  # 只要是访问的这个路径，一律都被路由到上面指定的服务







